# Generated by Django 2.1.9 on 2021-08-05 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=music.models.song_icon_upload_location)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=music.models.song_cover_upload_location)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='django_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.song_cover_upload_location),
        ),
        migrations.AddField(
            model_name='song',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.song_icon_upload_location),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='music.Category'),
            preserve_default=False,
        ),
    ]
