# Generated by Django 2.1.9 on 2021-08-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210807_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
