# Generated by Django 2.2.16 on 2021-08-09 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210807_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
    ]
